### ISSUE TITLE
长按点击事件有个bug,会触发单击事件

### ISSUE THREAD

**Issue by hcs-xph** [hnsugar/MultiImageViewLayout#1]
当长按图片会触发OnLongClick事件，当松开后又会触发OnClick。

**Comment by itgowo** [comment]
我记得以前我专门做了处理，你查一下是不是自己添加了onclick监听，view本身提供了setOnItemClickListener方法，这个项目我打算重写，用gridlayout实现，感觉有缺陷

**Comment by hcs-xph** [comment]
@hnsugar 刚刚看了下源码是因为你在
`mImageView.setOnLongClickListener(new OnLongClickListener() {
            @Override
            public boolean onLongClick(View v) {
                if (mOnItemClickListener != null) {
                    mOnItemClickListener.onItemLongClick(v, (Integer) v.getTag(R.id.FriendLife_Position),PressX[0],PressY[0]);
                }
                return false;
            }
        });`
这里返回的false的原因。改成true就好了

**Comment by itgowo** [comment]
谢谢提醒，我记得了，确实改过，好像没有提交。。。。。疏忽了O(∩_∩)O哈哈~
